using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace IppCli.Generators;

/// <summary>
/// Incremental Roslyn Source Generator that automatically generates Spectre.Console CLI settings
/// classes for IPP request models decorated with <c>[GenerateCliSettings]</c>.
/// </summary>
/// <remarks>
/// <para>
/// <b>How it works:</b>
/// </para>
/// <list type="number">
///   <item>
///     <term>Post-Initialization:</term>
///     <description>
///       Emits the marker attribute <c>IppCli.Attributes.GenerateCliSettingsAttribute</c> into the compilation
///       so consumers can decorate their partial command settings classes without external assembly dependencies.
///     </description>
///   </item>
///   <item>
///     <term>Syntax &amp; Semantic Analysis:</term>
///     <description>
///       Scans for candidate <c>partial</c> classes decorated with <c>[GenerateCliSettings]</c>.
///       Inspects the attribute configuration for:
///       <list type="bullet">
///         <item><description><c>PropertyName</c>: The property name on the settings class hosting the IPP request object (default: <c>"Request"</c>).</description></item>
///         <item><description><c>MaxNestingDepth</c>: Maximum recursion level to flatten nested complex objects into individual CLI options (default: <c>1</c>).</description></item>
///       </list>
///       Discovers the target IPP request model type (e.g. <c>PrintJobRequest</c>, <c>GetPrinterAttributesRequest</c>) from the class hierarchy.
///     </description>
///   </item>
///   <item>
///     <term>Source Code Generation:</term>
///     <description>
///       Generates a companion partial class containing:
///       <list type="bullet">
///         <item>
///           <b>Default Initialization:</b> A constructor setting standard IPP defaults (e.g. <c>Version = 1.1</c>, <c>RequestId = 1</c>,
///           and populating <c>OperationAttributes.RequestingUserName</c> from the current environment).
///         </item>
///         <item>
///           <b>Attribute Group Flattening:</b> IPP attribute groups (e.g. <c>OperationAttributes</c>, <c>JobTemplateAttributes</c>,
///           <c>PrinterAttributes</c>, <c>DocumentTemplateAttributes</c>) are grouped and assigned short CLI option prefixes
///           (<c>--op-*</c>, <c>--jta-*</c>, <c>--pa-*</c>, <c>--dta-*</c>) as well as dedicated raw JSON bypass options (<c>--op-json</c>, etc.).
///         </item>
///         <item>
///           <b>Property Mapping:</b> Every request property is mapped to a Spectre.Console <c>[CommandOption]</c> property with
///           appropriate descriptions and type converters:
///           <list type="bullet">
///             <item><description><i>Streams / Files:</i> Mapped to file paths (<c>--document &lt;PATH&gt;</c>).</description></item>
///             <item><description><i>URIs &amp; IPP Versions:</i> Mapped with custom type converters (<c>UriTypeConverter</c>, <c>IppVersionTypeConverter</c>).</description></item>
///             <item><description><i>Enums &amp; SmartEnums:</i> Mapped with case-insensitive enum / smart enum converters.</description></item>
///             <item><description><i>Arrays &amp; Collections:</i> Mapped to comma-separated values or JSON payload options.</description></item>
///             <item><description><i>Primitives &amp; Flags:</i> Mapped to typed integer, string, or boolean flag switches.</description></item>
///             <item><description><i>Complex Nested Types:</i> Mapped to JSON string/file parameters (<c>&lt;JSON&gt;</c>) and recursively expanded into individual options up to <c>MaxNestingDepth</c>.</description></item>
///           </list>
///         </item>
///         <item>
///           <b>Transparent Delegation:</b> Generated CLI property getters and setters directly read from and mutate the underlying IPP request model,
///           ensuring intermediate null container hierarchies are lazily initialized.
///         </item>
///       </list>
///     </description>
///   </item>
/// </list>
/// </remarks>
[Generator]
public class CliSettingsSourceGenerator : IIncrementalGenerator
{
    private const int DefaultMaxNestingDepth = 1;

    private const string AttributeSource = @"// <auto-generated/>
#nullable enable
using System;

namespace IppCli.Attributes
{
    [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
    public sealed class GenerateCliSettingsAttribute : Attribute
    {
        public string PropertyName { get; }
        public int MaxNestingDepth { get; set; }

        public GenerateCliSettingsAttribute(string propertyName = ""Request"", int maxNestingDepth = 1)
        {
            PropertyName = propertyName;
            MaxNestingDepth = maxNestingDepth;
        }
    }
}
";


    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. Post-initialization: emit the marker attribute
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("GenerateCliSettingsAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8));
        });

        // 2. Syntax provider: find classes decorated with [GenerateCliSettings]
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsCandidateClass(node),
                transform: static (ctx, _) => GetClassSemanticTarget(ctx))
            .Where(static target => target != null);

        // 3. Combine with compilation
        var compilationAndClasses = context.CompilationProvider.Combine(classDeclarations.Collect());

        // 4. Generate source for each target
        context.RegisterSourceOutput(compilationAndClasses, static (spc, source) =>
        {
            var (compilation, targets) = source;
            var processed = new HashSet<string>();

            foreach (var target in targets)
            {
                if (target == null) continue;
                var (classSymbol, requestTypeSymbol, propertyName, maxNestingDepth) = target.Value;

                var key = classSymbol.ToDisplayString();
                if (!processed.Add(key)) continue;

                var generatedCode = GenerateSettingsSource(classSymbol, requestTypeSymbol, propertyName, maxNestingDepth);
                if (!string.IsNullOrEmpty(generatedCode))
                {
                    var parentName = classSymbol.ContainingType != null ? $"{classSymbol.ContainingType.Name}_" : "";
                    var fileName = $"{parentName}{classSymbol.Name}.g.cs";
                    spc.AddSource(fileName, SourceText.From(generatedCode, Encoding.UTF8));
                }
            }
        });
    }

    private static bool IsCandidateClass(SyntaxNode node)
    {
        if (node is not ClassDeclarationSyntax cds) return false;
        if (!cds.Modifiers.Any(SyntaxKind.PartialKeyword)) return false;

        // Must have at least one attribute
        return cds.AttributeLists.Count > 0;
    }

    private static (INamedTypeSymbol ClassSymbol, INamedTypeSymbol RequestTypeSymbol, string PropertyName, int MaxNestingDepth)? GetClassSemanticTarget(GeneratorSyntaxContext ctx)
    {
        var classDeclaration = (ClassDeclarationSyntax)ctx.Node;
        if (ctx.SemanticModel.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol classSymbol)
        {
            return null;
        }

        // Check for [GenerateCliSettings] attribute
        foreach (var attr in classSymbol.GetAttributes())
        {
            if (attr.AttributeClass?.Name is "GenerateCliSettingsAttribute" or "GenerateCliSettings")
            {
                var propName = "Request";
                var maxNestingDepth = DefaultMaxNestingDepth;

                if (attr.ConstructorArguments.Length > 0 && attr.ConstructorArguments[0].Value is string customPropName && !string.IsNullOrWhiteSpace(customPropName))
                {
                    propName = customPropName;
                }

                if (attr.ConstructorArguments.Length > 1 && attr.ConstructorArguments[1].Value is int customDepth)
                {
                    maxNestingDepth = customDepth;
                }

                foreach (var namedArg in attr.NamedArguments)
                {
                    if (namedArg.Key == "MaxNestingDepth" && namedArg.Value.Value is int namedDepth)
                    {
                        maxNestingDepth = namedDepth;
                    }
                    else if (namedArg.Key == "PropertyName" && namedArg.Value.Value is string namedPropName && !string.IsNullOrWhiteSpace(namedPropName))
                    {
                        propName = namedPropName;
                    }
                }

                var propSymbol = FindProperty(classSymbol, propName);
                if (propSymbol?.Type is INamedTypeSymbol reqSymbol)
                {
                    return (classSymbol, reqSymbol, propName, maxNestingDepth);
                }
            }
        }

        return null;
    }

    private static IPropertySymbol? FindProperty(ITypeSymbol? type, string name)
    {
        var current = type;
        while (current != null && current.SpecialType != SpecialType.System_Object)
        {
            var prop = current.GetMembers(name).OfType<IPropertySymbol>().FirstOrDefault(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic);
            if (prop != null) return prop;
            current = current.BaseType;
        }
        return null;
    }

    private static List<IPropertySymbol> GetAllProperties(ITypeSymbol? type)
    {
        var list = new List<IPropertySymbol>();
        var seen = new HashSet<string>();
        var current = type;
        while (current != null && current.SpecialType != SpecialType.System_Object)
        {
            foreach (var member in current.GetMembers().OfType<IPropertySymbol>())
            {
                // Skip explicit interface implementations, non-public, indexers, static, or read-only properties
                if (member.DeclaredAccessibility != Accessibility.Public ||
                    member.SetMethod == null ||
                    member.SetMethod.DeclaredAccessibility != Accessibility.Public ||
                    member.IsReadOnly ||
                    member.ExplicitInterfaceImplementations.Length > 0 ||
                    member.Name.Contains(".") ||
                    member.IsStatic ||
                    member.IsIndexer)
                {
                    continue;
                }

                if (seen.Add(member.Name))
                {
                    list.Add(member);
                }
            }
            current = current.BaseType;
        }
        return list;
    }

    private static string GenerateSettingsSource(INamedTypeSymbol classSymbol, INamedTypeSymbol requestTypeSymbol, string propertyName, int maxNestingDepth)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.IO;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.ComponentModel;");
        sb.AppendLine("using Spectre.Console.Cli;");
        sb.AppendLine("using SharpIpp.Models.Requests;");
        sb.AppendLine("using SharpIpp.Protocol.Models;");
        sb.AppendLine();

        var ns = classSymbol.ContainingNamespace.IsGlobalNamespace ? null : classSymbol.ContainingNamespace.ToDisplayString();
        if (ns != null)
        {
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
        }

        var containingTypes = new Stack<INamedTypeSymbol>();
        var parent = classSymbol.ContainingType;
        while (parent != null)
        {
            containingTypes.Push(parent);
            parent = parent.ContainingType;
        }

        var indent = "";
        while (containingTypes.Count > 0)
        {
            var ct = containingTypes.Pop();
            sb.AppendLine($"{indent}public partial class {ct.Name}");
            sb.AppendLine($"{indent}{{");
            indent += "    ";
        }

        sb.AppendLine($"{indent}public partial class {classSymbol.Name}");
        sb.AppendLine($"{indent}{{");
        var bodyIndent = indent + "    ";

        var allRequestProps = GetAllProperties(requestTypeSymbol);

        // Generate constructor initializing defaults
        sb.AppendLine($"{bodyIndent}public {classSymbol.Name}()");
        sb.AppendLine($"{bodyIndent}{{");
        sb.AppendLine($"{bodyIndent}    {propertyName}.Version = new IppVersion(1, 1);");
        sb.AppendLine($"{bodyIndent}    {propertyName}.RequestId = 1;");

        // If request has OperationAttributes, initialize it and set default RequestingUserName
        var opAttrProp = allRequestProps.FirstOrDefault(p => p.Name == "OperationAttributes");
        if (opAttrProp != null && opAttrProp.Type is INamedTypeSymbol opAttrType)
        {
            var cleanOpTypeName = opAttrType.WithNullableAnnotation(NullableAnnotation.NotAnnotated).ToDisplayString();
            sb.AppendLine($"{bodyIndent}    {propertyName}.OperationAttributes = new {cleanOpTypeName}();");
            var allOpProps = GetAllProperties(opAttrType);
            if (allOpProps.Any(p => p.Name == "RequestingUserName"))
            {
                sb.AppendLine($"{bodyIndent}    {propertyName}.OperationAttributes.RequestingUserName = Environment.UserName ?? \"anonymous\";");
            }
        }
        sb.AppendLine($"{bodyIndent}}}");
        sb.AppendLine();

        // Inspect and generate all request properties
        foreach (var member in allRequestProps)
        {
            if (IsAttributeGroup(member) && member.Type is INamedTypeSymbol attrType)
            {
                var (propPrefix, cliPrefix, sectionTitle, jsonCliOption) = GetAttributeGroupInfo(member.Name);
                var acronym = cliPrefix.Trim('-', ' ');
                sb.AppendLine($"{bodyIndent}// ==========================================================");
                sb.AppendLine($"{bodyIndent}// {sectionTitle} ({cliPrefix}*)");
                sb.AppendLine($"{bodyIndent}// ==========================================================");
                GenerateNestedAttributes(sb, bodyIndent, member.Name, propPrefix, acronym, jsonCliOption, attrType, propertyName, maxNestingDepth);
            }
            else
            {
                GenerateProperty(sb, bodyIndent, containerPropertyName: null, propPrefix: "", cliSegments: Array.Empty<string>(), member, propertyName, depth: 0, maxNestingDepth: maxNestingDepth);
            }
        }

        // Close class
        sb.AppendLine($"{indent}}}");

        // Close containing classes
        while (indent.Length > 0)
        {
            indent = indent.Substring(0, Math.Max(0, indent.Length - 4));
            sb.AppendLine($"{indent}}}");
        }

        return sb.ToString();
    }

    private static void GenerateNestedAttributes(
        StringBuilder sb,
        string indent,
        string containerPropertyName,
        string propPrefix,
        string acronym,
        string jsonCliOption,
        INamedTypeSymbol attrType,
        string targetPropertyName,
        int maxNestingDepth)
    {
        GenerateContainerJsonOption(sb, indent, containerPropertyName, propPrefix, jsonCliOption, attrType, targetPropertyName);

        var properties = GetAllProperties(attrType);

        foreach (var prop in properties)
        {
            GenerateProperty(sb, indent, containerPropertyName, propPrefix, new[] { acronym }, prop, targetPropertyName, depth: 1, maxNestingDepth: maxNestingDepth);
        }
    }

    private static void GenerateProperty(
        StringBuilder sb,
        string indent,
        string? containerPropertyName,
        string propPrefix,
        IReadOnlyList<string> cliSegments,
        IPropertySymbol prop,
        string targetPropertyName,
        int depth = 0,
        int maxNestingDepth = DefaultMaxNestingDepth)
    {
        var propName = prop.Name;
        var csharpPropName = $"{propPrefix}{propName}";
        var kebabName = ToKebabCase(propName);
        var optName = BuildOptionAliases(cliSegments, kebabName, "<VALUE>");

        var unwrappedType = GetUnwrappedType(prop.Type);
        var unwrappedTypeName = unwrappedType.Name;
        var fullTypeName = unwrappedType.ToDisplayString();

        if (IsStreamType(prop.Type))
        {
            var streamOptName = BuildOptionAliases(cliSegments, kebabName, "<PATH>");
            var streamDesc = $"Path to the {propName.ToLowerInvariant()} file";
            GenerateStreamProperty(sb, indent, csharpPropName, streamOptName, streamDesc);
        }
        else if (unwrappedTypeName == "Uri" || fullTypeName == "System.Uri")
        {
            var uriDesc = $"URI value for {propName}";
            GenerateUriProperty(sb, indent, containerPropertyName, csharpPropName, optName, propName, targetPropertyName, uriDesc);
        }
        else if (unwrappedTypeName == "IppVersion" || fullTypeName == "SharpIpp.Protocol.Models.IppVersion")
        {
            var verDesc = $"IPP Version value for {propName}";
            GenerateIppVersionProperty(sb, indent, containerPropertyName, csharpPropName, optName, propName, targetPropertyName, verDesc);
        }
        else if (prop.Type is IArrayTypeSymbol arrayType)
        {
            if (IsIppCollection(arrayType.ElementType) || IsComplexType(arrayType.ElementType))
            {
                var collOptName = BuildOptionAliases(cliSegments, kebabName, "<JSON>");
                var collDesc = $"JSON array string or @file.json for {propName}";
                GenerateComplexArrayProperty(sb, indent, containerPropertyName, csharpPropName, collOptName, propName, arrayType.ElementType, targetPropertyName, collDesc);
            }
            else
            {
                var arrDesc = $"Comma-separated array values for {propName}";
                GenerateArrayProperty(sb, indent, containerPropertyName, csharpPropName, optName, propName, arrayType, targetPropertyName, arrDesc);
            }
        }
        else if (unwrappedType.TypeKind == TypeKind.Enum)
        {
            var enumDesc = $"Enum value for {propName}";
            GenerateEnumProperty(sb, indent, containerPropertyName, csharpPropName, optName, propName, unwrappedType, targetPropertyName, enumDesc);
        }
        else if (unwrappedType.AllInterfaces.Any(i => i.Name == "ISmartEnum"))
        {
            var smartDesc = $"{unwrappedType.Name} value for {propName}";
            GenerateSmartEnumProperty(sb, indent, containerPropertyName, csharpPropName, optName, propName, unwrappedType, targetPropertyName, smartDesc);
        }
        else if (unwrappedType.SpecialType == SpecialType.System_Boolean)
        {
            var boolDesc = $"Boolean flag for {propName}";
            var boolOptName = BuildOptionAliases(cliSegments, kebabName);
            GenerateBoolProperty(sb, indent, containerPropertyName, csharpPropName, boolOptName, propName, targetPropertyName, boolDesc);
        }
        else if (unwrappedType.SpecialType == SpecialType.System_Int32)
        {
            var isNullable = prop.Type.Name == "Nullable";
            var intDesc = $"Integer value for {propName}";
            GenerateIntProperty(sb, indent, containerPropertyName, csharpPropName, optName, propName, targetPropertyName, intDesc, isNullable);
        }
        else if (unwrappedType.SpecialType == SpecialType.System_String)
        {
            var strDesc = $"String value for {propName}";
            GenerateStringProperty(sb, indent, containerPropertyName, csharpPropName, optName, propName, targetPropertyName, strDesc);
        }
        else if (unwrappedTypeName == "DateTimeOffset" || fullTypeName == "System.DateTimeOffset")
        {
            var dtDesc = $"DateTimeOffset value for {propName}";
            GenerateDateTimeOffsetProperty(sb, indent, containerPropertyName, csharpPropName, optName, propName, targetPropertyName, dtDesc);
        }
        else if (unwrappedTypeName == "Range" || fullTypeName == "SharpIpp.Protocol.Models.Range")
        {
            var rangeDesc = $"Range value (e.g. 1-100 or 5) for {propName}";
            GenerateRangeProperty(sb, indent, containerPropertyName, csharpPropName, optName, propName, targetPropertyName, rangeDesc);
        }
        else if (IsIppCollection(unwrappedType) || IsComplexType(unwrappedType))
        {
            var collOptName = BuildOptionAliases(cliSegments, kebabName, "<JSON>");
            var collDesc = $"JSON string or @file.json for {propName}";
            GenerateComplexProperty(sb, indent, containerPropertyName, csharpPropName, collOptName, propName, unwrappedType, targetPropertyName, collDesc);

            if (depth < maxNestingDepth && unwrappedType is INamedTypeSymbol complexNamedType)
            {
                var subProperties = GetAllProperties(complexNamedType);
                var nextContainer = string.IsNullOrEmpty(containerPropertyName) ? propName : $"{containerPropertyName}.{propName}";
                var nextPropPrefix = $"{propPrefix}{propName}";
                var nextSegments = new List<string>(cliSegments) { kebabName };

                foreach (var subProp in subProperties)
                {
                    GenerateProperty(sb, indent, nextContainer, nextPropPrefix, nextSegments, subProp, targetPropertyName, depth + 1, maxNestingDepth);
                }
            }
        }
        else
        {
            var fbDesc = $"Value for {propName}";
            GenerateFallbackProperty(sb, indent, containerPropertyName, csharpPropName, optName, propName, prop.Type, targetPropertyName, fbDesc);
        }
    }

    private static string GetSafePath(string? container)
    {
        if (string.IsNullOrEmpty(container)) return "";
        return string.Join("?.", container!.Split('.'));
    }

    private static void EmitContainerNullChecks(StringBuilder sb, string indent, string targetPropertyName, string? container)
    {
        if (string.IsNullOrEmpty(container)) return;
        var parts = container!.Split('.');
        var chain = "";
        foreach (var part in parts)
        {
            chain = string.IsNullOrEmpty(chain) ? part : $"{chain}.{part}";
            sb.AppendLine($"{indent}            {targetPropertyName}.{chain} ??= new();");
        }
    }

    private static string BuildOptionAliases(IReadOnlyList<string> segments, string kebabName, string suffix = "")
    {
        var suffixPart = string.IsNullOrEmpty(suffix) ? "" : $" {suffix}";
        var allParts = new List<string>(segments) { kebabName };
        return $"--{string.Join("-", allParts)}{suffixPart}";
    }

    private static bool IsStreamType(ITypeSymbol type)
    {
        var current = type;
        while (current != null)
        {
            if (current.ToDisplayString() == "System.IO.Stream" || current.Name == "Stream")
            {
                return true;
            }
            current = current.BaseType;
        }
        return false;
    }

    private static ITypeSymbol GetUnwrappedType(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol nts && nts.IsGenericType && (nts.Name == "Nullable" || nts.ConstructedFrom.SpecialType == SpecialType.System_Nullable_T))
        {
            return nts.TypeArguments[0];
        }
        return type;
    }

    private static void GenerateStreamProperty(
        StringBuilder sb,
        string indent,
        string csharpPropName,
        string aliases,
        string description)
    {
        var fieldName = $"_{csharpPropName.Substring(0, 1).ToLowerInvariant()}{csharpPropName.Substring(1)}";
        sb.AppendLine($"{indent}private string? {fieldName};");
        sb.AppendLine($"{indent}[CommandOption(\"{aliases}\")]");
        sb.AppendLine($"{indent}[Description(\"{description}\")]");
        sb.AppendLine($"{indent}public string? {csharpPropName}");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    get => {fieldName};");
        sb.AppendLine($"{indent}    set => {fieldName} = value;");
        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
    }

    private static void GenerateUriProperty(
        StringBuilder sb,
        string indent,
        string? container,
        string csharpPropName,
        string aliases,
        string propName,
        string targetPropertyName,
        string description)
    {
        sb.AppendLine($"{indent}[CommandOption(\"{aliases}\")]");
        sb.AppendLine($"{indent}[Description(\"{description}\")]");
        sb.AppendLine($"{indent}public string? {csharpPropName}");
        sb.AppendLine($"{indent}{{");
        if (string.IsNullOrEmpty(container))
        {
            sb.AppendLine($"{indent}    get => {targetPropertyName}.{propName}?.ToString();");
            sb.AppendLine($"{indent}    set");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        if (!string.IsNullOrWhiteSpace(value))");
            sb.AppendLine($"{indent}        {{");
            sb.AppendLine($"{indent}            {targetPropertyName}.{propName} = new Uri(value, UriKind.Absolute);");
            sb.AppendLine($"{indent}        }}");
            sb.AppendLine($"{indent}    }}");
        }
        else
        {
            sb.AppendLine($"{indent}    get => {targetPropertyName}.{GetSafePath(container)}?.{propName}?.ToString();");
            sb.AppendLine($"{indent}    set");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        if (!string.IsNullOrWhiteSpace(value))");
            sb.AppendLine($"{indent}        {{");
            EmitContainerNullChecks(sb, indent, targetPropertyName, container);
            sb.AppendLine($"{indent}            var uri = new Uri(value, UriKind.Absolute);");
            sb.AppendLine($"{indent}            {targetPropertyName}.{container}.{propName} = uri;");
            sb.AppendLine($"{indent}        }}");
            sb.AppendLine($"{indent}    }}");
        }
        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
    }

    private static void GenerateIppVersionProperty(
        StringBuilder sb,
        string indent,
        string? container,
        string csharpPropName,
        string aliases,
        string propName,
        string targetPropertyName,
        string description)
    {
        sb.AppendLine($"{indent}[CommandOption(\"{aliases}\")]");
        sb.AppendLine($"{indent}[Description(\"{description}\")]");
        sb.AppendLine($"{indent}public string? {csharpPropName}");
        sb.AppendLine($"{indent}{{");
        if (string.IsNullOrEmpty(container))
        {
            sb.AppendLine($"{indent}    get => {targetPropertyName}.{propName}.ToString();");
            sb.AppendLine($"{indent}    set");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        if (!string.IsNullOrWhiteSpace(value))");
            sb.AppendLine($"{indent}        {{");
            sb.AppendLine($"{indent}            {targetPropertyName}.{propName} = new IppVersion(value);");
            sb.AppendLine($"{indent}        }}");
            sb.AppendLine($"{indent}    }}");
        }
        else
        {
            sb.AppendLine($"{indent}    get => {targetPropertyName}.{GetSafePath(container)}?.{propName}?.ToString();");
            sb.AppendLine($"{indent}    set");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        if (!string.IsNullOrWhiteSpace(value))");
            sb.AppendLine($"{indent}        {{");
            EmitContainerNullChecks(sb, indent, targetPropertyName, container);
            sb.AppendLine($"{indent}            {targetPropertyName}.{container}.{propName} = new IppVersion(value);");
            sb.AppendLine($"{indent}        }}");
            sb.AppendLine($"{indent}    }}");
        }
        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
    }

    private static void GenerateSmartEnumProperty(
        StringBuilder sb,
        string indent,
        string? container,
        string csharpPropName,
        string aliases,
        string propName,
        ITypeSymbol type,
        string targetPropertyName,
        string description)
    {
        var typeName = type.ToDisplayString();
        sb.AppendLine($"{indent}[CommandOption(\"{aliases}\")]");
        sb.AppendLine($"{indent}[Description(\"{description}\")]");
        sb.AppendLine($"{indent}public {typeName}? {csharpPropName}");
        sb.AppendLine($"{indent}{{");
        if (string.IsNullOrEmpty(container))
        {
            sb.AppendLine($"{indent}    get => {targetPropertyName}.{propName};");
            sb.AppendLine($"{indent}    set");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        if (value.HasValue)");
            sb.AppendLine($"{indent}        {{");
            sb.AppendLine($"{indent}            {targetPropertyName}.{propName} = value.Value;");
            sb.AppendLine($"{indent}        }}");
            sb.AppendLine($"{indent}    }}");
        }
        else
        {
            sb.AppendLine($"{indent}    get => {targetPropertyName}.{GetSafePath(container)}?.{propName};");
            sb.AppendLine($"{indent}    set");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        if (value.HasValue)");
            sb.AppendLine($"{indent}        {{");
            EmitContainerNullChecks(sb, indent, targetPropertyName, container);
            sb.AppendLine($"{indent}            {targetPropertyName}.{container}.{propName} = value.Value;");
            sb.AppendLine($"{indent}        }}");
            sb.AppendLine($"{indent}    }}");
        }
        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
    }

    private static void GenerateArrayProperty(
        StringBuilder sb,
        string indent,
        string? container,
        string csharpPropName,
        string aliases,
        string propName,
        IArrayTypeSymbol arrayType,
        string targetPropertyName,
        string description)
    {
        var elemType = arrayType.ElementType;
        var elemTypeName = elemType.ToDisplayString();

        sb.AppendLine($"{indent}private string? _{csharpPropName.ToLowerInvariant()};");
        sb.AppendLine($"{indent}[CommandOption(\"{aliases}\")]");
        sb.AppendLine($"{indent}[Description(\"{description}\")]");
        sb.AppendLine($"{indent}public string? {csharpPropName}");
        sb.AppendLine($"{indent}{{");
        if (string.IsNullOrEmpty(container))
        {
            sb.AppendLine($"{indent}    get => {targetPropertyName}.{propName} != null ? string.Join(\",\", {targetPropertyName}.{propName}.Select(x => x.ToString())) : _{csharpPropName.ToLowerInvariant()};");
            sb.AppendLine($"{indent}    set");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        _{csharpPropName.ToLowerInvariant()} = value;");
            sb.AppendLine($"{indent}        if (string.IsNullOrWhiteSpace(value)) return;");
            if (elemType.SpecialType == SpecialType.System_String)
            {
                sb.AppendLine($"{indent}        {targetPropertyName}.{propName} = value.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);");
            }
            else if (elemType.SpecialType == SpecialType.System_Int32)
            {
                sb.AppendLine($"{indent}        {targetPropertyName}.{propName} = value.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries).Select(int.Parse).ToArray();");
            }
            else if (elemType.TypeKind == TypeKind.Enum)
            {
                sb.AppendLine($"{indent}        {targetPropertyName}.{propName} = value.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries).Select(s => ({elemTypeName})Enum.Parse(typeof({elemTypeName}), s, true)).ToArray();");
            }
            else if (elemType.Name == "IdentifyAction")
            {
                sb.AppendLine($"{indent}        {targetPropertyName}.{propName} = value.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries).Select(s => new SharpIpp.Protocol.Models.IdentifyAction(s)).ToArray();");
            }
            else if (elemType.Name == "Range")
            {
                sb.AppendLine($"{indent}        {targetPropertyName}.{propName} = value.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries).Select(s => {{ var parts = s.Split('-'); return parts.Length > 1 ? new SharpIpp.Protocol.Models.Range(int.Parse(parts[0]), int.Parse(parts[1])) : new SharpIpp.Protocol.Models.Range(int.Parse(parts[0]), int.Parse(parts[0])); }}).ToArray();");
            }
            else if (elemType.AllInterfaces.Any(i => i.Name == "ISmartEnum"))
            {
                sb.AppendLine($"{indent}        {targetPropertyName}.{propName} = value.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries).Select(s => new {elemTypeName}(s)).ToArray();");
            }
            sb.AppendLine($"{indent}    }}");
        }
        else
        {
            sb.AppendLine($"{indent}    get => {targetPropertyName}.{GetSafePath(container)}?.{propName} != null ? string.Join(\",\", {targetPropertyName}.{container}.{propName}!.Select(x => x.ToString())) : _{csharpPropName.ToLowerInvariant()};");
            sb.AppendLine($"{indent}    set");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        _{csharpPropName.ToLowerInvariant()} = value;");
            sb.AppendLine($"{indent}        if (string.IsNullOrWhiteSpace(value)) return;");
            EmitContainerNullChecks(sb, indent, targetPropertyName, container);

            if (elemType.SpecialType == SpecialType.System_String)
            {
                sb.AppendLine($"{indent}        {targetPropertyName}.{container}.{propName} = value.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);");
            }
            else if (elemType.SpecialType == SpecialType.System_Int32)
            {
                sb.AppendLine($"{indent}        {targetPropertyName}.{container}.{propName} = value.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries).Select(int.Parse).ToArray();");
            }
            else if (elemType.TypeKind == TypeKind.Enum)
            {
                sb.AppendLine($"{indent}        {targetPropertyName}.{container}.{propName} = value.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries).Select(s => ({elemTypeName})Enum.Parse(typeof({elemTypeName}), s, true)).ToArray();");
            }
            else if (elemType.Name == "IdentifyAction")
            {
                sb.AppendLine($"{indent}        {targetPropertyName}.{container}.{propName} = value.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries).Select(s => new SharpIpp.Protocol.Models.IdentifyAction(s)).ToArray();");
            }
            else if (elemType.Name == "Range")
            {
                sb.AppendLine($"{indent}        {targetPropertyName}.{container}.{propName} = value.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries).Select(s => {{ var parts = s.Split('-'); return parts.Length > 1 ? new SharpIpp.Protocol.Models.Range(int.Parse(parts[0]), int.Parse(parts[1])) : new SharpIpp.Protocol.Models.Range(int.Parse(parts[0]), int.Parse(parts[0])); }}).ToArray();");
            }
            else if (elemType.AllInterfaces.Any(i => i.Name == "ISmartEnum"))
            {
                sb.AppendLine($"{indent}        {targetPropertyName}.{container}.{propName} = value.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries).Select(s => new {elemTypeName}(s)).ToArray();");
            }
            sb.AppendLine($"{indent}    }}");
        }
        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
    }

    private static void GenerateEnumProperty(
        StringBuilder sb,
        string indent,
        string? container,
        string csharpPropName,
        string aliases,
        string propName,
        ITypeSymbol type,
        string targetPropertyName,
        string description)
    {
        var enumType = type is INamedTypeSymbol nts && nts.IsGenericType ? nts.TypeArguments[0] : type;
        var enumTypeName = enumType.ToDisplayString();

        sb.AppendLine($"{indent}[CommandOption(\"{aliases}\")]");
        sb.AppendLine($"{indent}[Description(\"{description}\")]");
        sb.AppendLine($"{indent}public {enumTypeName}? {csharpPropName}");
        sb.AppendLine($"{indent}{{");
        if (string.IsNullOrEmpty(container))
        {
            sb.AppendLine($"{indent}    get => {targetPropertyName}.{propName};");
            sb.AppendLine($"{indent}    set");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        if (value.HasValue)");
            sb.AppendLine($"{indent}        {{");
            sb.AppendLine($"{indent}            {targetPropertyName}.{propName} = value.Value;");
            sb.AppendLine($"{indent}        }}");
            sb.AppendLine($"{indent}    }}");
        }
        else
        {
            sb.AppendLine($"{indent}    get => {targetPropertyName}.{GetSafePath(container)}?.{propName};");
            sb.AppendLine($"{indent}    set");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        if (value.HasValue)");
            sb.AppendLine($"{indent}        {{");
            EmitContainerNullChecks(sb, indent, targetPropertyName, container);
            sb.AppendLine($"{indent}            {targetPropertyName}.{container}.{propName} = value.Value;");
            sb.AppendLine($"{indent}        }}");
            sb.AppendLine($"{indent}    }}");
        }
        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
    }

    private static void GenerateBoolProperty(
        StringBuilder sb,
        string indent,
        string? container,
        string csharpPropName,
        string aliases,
        string propName,
        string targetPropertyName,
        string description)
    {
        sb.AppendLine($"{indent}[CommandOption(\"{aliases}\")]");
        sb.AppendLine($"{indent}[Description(\"{description}\")]");
        sb.AppendLine($"{indent}public bool {csharpPropName}");
        sb.AppendLine($"{indent}{{");
        if (string.IsNullOrEmpty(container))
        {
            sb.AppendLine($"{indent}    get => {targetPropertyName}.{propName};");
            sb.AppendLine($"{indent}    set => {targetPropertyName}.{propName} = value;");
        }
        else
        {
            sb.AppendLine($"{indent}    get => {targetPropertyName}.{GetSafePath(container)}?.{propName} ?? false;");
            sb.AppendLine($"{indent}    set");
            sb.AppendLine($"{indent}    {{");
            EmitContainerNullChecks(sb, indent, targetPropertyName, container);
            sb.AppendLine($"{indent}        {targetPropertyName}.{container}.{propName} = value;");
            sb.AppendLine($"{indent}    }}");
        }
        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
    }

    private static void GenerateIntProperty(
        StringBuilder sb,
        string indent,
        string? container,
        string csharpPropName,
        string aliases,
        string propName,
        string targetPropertyName,
        string description,
        bool isNullable)
    {
        var typeName = (string.IsNullOrEmpty(container) && !isNullable) ? "int" : "int?";

        sb.AppendLine($"{indent}[CommandOption(\"{aliases}\")]");
        sb.AppendLine($"{indent}[Description(\"{description}\")]");
        sb.AppendLine($"{indent}public {typeName} {csharpPropName}");
        sb.AppendLine($"{indent}{{");
        if (string.IsNullOrEmpty(container))
        {
            sb.AppendLine($"{indent}    get => {targetPropertyName}.{propName};");
            sb.AppendLine($"{indent}    set => {targetPropertyName}.{propName} = value;");
        }
        else
        {
            sb.AppendLine($"{indent}    get => {targetPropertyName}.{GetSafePath(container)}?.{propName};");
            sb.AppendLine($"{indent}    set");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        if (value.HasValue)");
            sb.AppendLine($"{indent}        {{");
            EmitContainerNullChecks(sb, indent, targetPropertyName, container);
            sb.AppendLine($"{indent}            {targetPropertyName}.{container}.{propName} = value.Value;");
            sb.AppendLine($"{indent}        }}");
            sb.AppendLine($"{indent}    }}");
        }
        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
    }

    private static void GenerateStringProperty(
        StringBuilder sb,
        string indent,
        string? container,
        string csharpPropName,
        string aliases,
        string propName,
        string targetPropertyName,
        string description)
    {
        sb.AppendLine($"{indent}[CommandOption(\"{aliases}\")]");
        sb.AppendLine($"{indent}[Description(\"{description}\")]");
        sb.AppendLine($"{indent}public string? {csharpPropName}");
        sb.AppendLine($"{indent}{{");
        if (string.IsNullOrEmpty(container))
        {
            sb.AppendLine($"{indent}    get => {targetPropertyName}.{propName};");
            sb.AppendLine($"{indent}    set => {targetPropertyName}.{propName} = value;");
        }
        else
        {
            sb.AppendLine($"{indent}    get => {targetPropertyName}.{GetSafePath(container)}?.{propName};");
            sb.AppendLine($"{indent}    set");
            sb.AppendLine($"{indent}    {{");
            EmitContainerNullChecks(sb, indent, targetPropertyName, container);
            sb.AppendLine($"{indent}        {targetPropertyName}.{container}.{propName} = value;");
            sb.AppendLine($"{indent}    }}");
        }
        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
    }

    private static void GenerateDateTimeOffsetProperty(
        StringBuilder sb,
        string indent,
        string? container,
        string csharpPropName,
        string aliases,
        string propName,
        string targetPropertyName,
        string description)
    {
        sb.AppendLine($"{indent}[CommandOption(\"{aliases}\")]");
        sb.AppendLine($"{indent}[Description(\"{description}\")]");
        sb.AppendLine($"{indent}public DateTimeOffset? {csharpPropName}");
        sb.AppendLine($"{indent}{{");
        if (string.IsNullOrEmpty(container))
        {
            sb.AppendLine($"{indent}    get => {targetPropertyName}.{propName};");
            sb.AppendLine($"{indent}    set");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        if (value.HasValue)");
            sb.AppendLine($"{indent}        {{");
            sb.AppendLine($"{indent}            {targetPropertyName}.{propName} = value.Value;");
            sb.AppendLine($"{indent}        }}");
            sb.AppendLine($"{indent}    }}");
        }
        else
        {
            sb.AppendLine($"{indent}    get => {targetPropertyName}.{GetSafePath(container)}?.{propName};");
            sb.AppendLine($"{indent}    set");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        if (value.HasValue)");
            sb.AppendLine($"{indent}        {{");
            EmitContainerNullChecks(sb, indent, targetPropertyName, container);
            sb.AppendLine($"{indent}            {targetPropertyName}.{container}.{propName} = value.Value;");
            sb.AppendLine($"{indent}        }}");
            sb.AppendLine($"{indent}    }}");
        }
        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
    }

    private static void GenerateFallbackProperty(
        StringBuilder sb,
        string indent,
        string? container,
        string csharpPropName,
        string aliases,
        string propName,
        ITypeSymbol type,
        string targetPropertyName,
        string description)
    {
        sb.AppendLine($"{indent}[CommandOption(\"{aliases}\")]");
        sb.AppendLine($"{indent}[Description(\"{description}\")]");
        sb.AppendLine($"{indent}public string? {csharpPropName}");
        sb.AppendLine($"{indent}{{");
        if (string.IsNullOrEmpty(container))
        {
            sb.AppendLine($"{indent}    get => {targetPropertyName}.{propName}?.ToString();");
            sb.AppendLine($"{indent}    set");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        // Fallback property mapping");
            sb.AppendLine($"{indent}    }}");
        }
        else
        {
            sb.AppendLine($"{indent}    get => {targetPropertyName}.{GetSafePath(container)}?.{propName}?.ToString();");
            sb.AppendLine($"{indent}    set");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        // Fallback property mapping");
            sb.AppendLine($"{indent}    }}");
        }
        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
    }

    private static void GenerateComplexProperty(
        StringBuilder sb,
        string indent,
        string? container,
        string csharpPropName,
        string aliases,
        string propName,
        ITypeSymbol type,
        string targetPropertyName,
        string description)
    {
        var isNullableValueType = type is INamedTypeSymbol nts && nts.IsGenericType && (nts.Name == "Nullable" || nts.ConstructedFrom.SpecialType == SpecialType.System_Nullable_T);
        var isNonNullableValueType = type.IsValueType && !isNullableValueType;
        var cleanTypeName = (isNullableValueType || isNonNullableValueType)
            ? (isNullableValueType ? ((INamedTypeSymbol)type).TypeArguments[0].ToDisplayString() : type.ToDisplayString())
            : type.WithNullableAnnotation(NullableAnnotation.NotAnnotated).ToDisplayString();

        var fieldName = $"_{csharpPropName.Substring(0, 1).ToLowerInvariant()}{csharpPropName.Substring(1)}";

        sb.AppendLine($"{indent}private string? {fieldName};");
        sb.AppendLine($"{indent}[CommandOption(\"{aliases}\")]");
        sb.AppendLine($"{indent}[Description(\"{description}\")]");
        sb.AppendLine($"{indent}public string? {csharpPropName}");
        sb.AppendLine($"{indent}{{");

        if (string.IsNullOrEmpty(container))
        {
            if (isNonNullableValueType)
            {
                sb.AppendLine($"{indent}    get => IppCli.Serialization.IppJsonHelper.Serialize({targetPropertyName}.{propName});");
                sb.AppendLine($"{indent}    set");
                sb.AppendLine($"{indent}    {{");
                sb.AppendLine($"{indent}        {fieldName} = value;");
                sb.AppendLine($"{indent}        if (!string.IsNullOrWhiteSpace(value))");
                sb.AppendLine($"{indent}        {{");
                sb.AppendLine($"{indent}            var parsed = IppCli.Serialization.IppJsonHelper.Deserialize<{cleanTypeName}?>(value);");
                sb.AppendLine($"{indent}            if (parsed.HasValue)");
                sb.AppendLine($"{indent}            {{");
                sb.AppendLine($"{indent}                {targetPropertyName}.{propName} = parsed.Value;");
                sb.AppendLine($"{indent}            }}");
                sb.AppendLine($"{indent}        }}");
                sb.AppendLine($"{indent}    }}");
            }
            else if (isNullableValueType)
            {
                sb.AppendLine($"{indent}    get => {targetPropertyName}.{propName}.HasValue ? IppCli.Serialization.IppJsonHelper.Serialize({targetPropertyName}.{propName}.Value) : {fieldName};");
                sb.AppendLine($"{indent}    set");
                sb.AppendLine($"{indent}    {{");
                sb.AppendLine($"{indent}        {fieldName} = value;");
                sb.AppendLine($"{indent}        if (!string.IsNullOrWhiteSpace(value))");
                sb.AppendLine($"{indent}        {{");
                sb.AppendLine($"{indent}            var parsed = IppCli.Serialization.IppJsonHelper.Deserialize<{cleanTypeName}?>(value);");
                sb.AppendLine($"{indent}            if (parsed.HasValue)");
                sb.AppendLine($"{indent}            {{");
                sb.AppendLine($"{indent}                {targetPropertyName}.{propName} = parsed.Value;");
                sb.AppendLine($"{indent}            }}");
                sb.AppendLine($"{indent}        }}");
                sb.AppendLine($"{indent}    }}");
            }
            else
            {
                sb.AppendLine($"{indent}    get => {targetPropertyName}.{propName} != null ? IppCli.Serialization.IppJsonHelper.Serialize({targetPropertyName}.{propName}) : {fieldName};");
                sb.AppendLine($"{indent}    set");
                sb.AppendLine($"{indent}    {{");
                sb.AppendLine($"{indent}        {fieldName} = value;");
                sb.AppendLine($"{indent}        if (!string.IsNullOrWhiteSpace(value))");
                sb.AppendLine($"{indent}        {{");
                sb.AppendLine($"{indent}            var parsed = IppCli.Serialization.IppJsonHelper.Deserialize<{cleanTypeName}>(value);");
                sb.AppendLine($"{indent}            if (parsed != null)");
                sb.AppendLine($"{indent}            {{");
                sb.AppendLine($"{indent}                {targetPropertyName}.{propName} = parsed;");
                sb.AppendLine($"{indent}            }}");
                sb.AppendLine($"{indent}        }}");
                sb.AppendLine($"{indent}    }}");
            }
        }
        else
        {
            if (isNonNullableValueType)
            {
                sb.AppendLine($"{indent}    get => {targetPropertyName}.{GetSafePath(container)} != null ? IppCli.Serialization.IppJsonHelper.Serialize({targetPropertyName}.{container}.{propName}) : {fieldName};");
                sb.AppendLine($"{indent}    set");
                sb.AppendLine($"{indent}    {{");
                sb.AppendLine($"{indent}        {fieldName} = value;");
                sb.AppendLine($"{indent}        if (!string.IsNullOrWhiteSpace(value))");
                sb.AppendLine($"{indent}        {{");
                sb.AppendLine($"{indent}            var parsed = IppCli.Serialization.IppJsonHelper.Deserialize<{cleanTypeName}?>(value);");
                sb.AppendLine($"{indent}            if (parsed.HasValue)");
                sb.AppendLine($"{indent}            {{");
                EmitContainerNullChecks(sb, indent, targetPropertyName, container);
                sb.AppendLine($"{indent}                {targetPropertyName}.{container}.{propName} = parsed.Value;");
                sb.AppendLine($"{indent}            }}");
                sb.AppendLine($"{indent}        }}");
                sb.AppendLine($"{indent}    }}");
            }
            else if (isNullableValueType)
            {
                sb.AppendLine($"{indent}    get => {targetPropertyName}.{GetSafePath(container)}?.{propName}.HasValue == true ? IppCli.Serialization.IppJsonHelper.Serialize({targetPropertyName}.{container}.{propName}.Value) : {fieldName};");
                sb.AppendLine($"{indent}    set");
                sb.AppendLine($"{indent}    {{");
                sb.AppendLine($"{indent}        {fieldName} = value;");
                sb.AppendLine($"{indent}        if (!string.IsNullOrWhiteSpace(value))");
                sb.AppendLine($"{indent}        {{");
                sb.AppendLine($"{indent}            var parsed = IppCli.Serialization.IppJsonHelper.Deserialize<{cleanTypeName}?>(value);");
                sb.AppendLine($"{indent}            if (parsed.HasValue)");
                sb.AppendLine($"{indent}            {{");
                EmitContainerNullChecks(sb, indent, targetPropertyName, container);
                sb.AppendLine($"{indent}                {targetPropertyName}.{container}.{propName} = parsed.Value;");
                sb.AppendLine($"{indent}            }}");
                sb.AppendLine($"{indent}        }}");
                sb.AppendLine($"{indent}    }}");
            }
            else
            {
                sb.AppendLine($"{indent}    get => {targetPropertyName}.{GetSafePath(container)}?.{propName} != null ? IppCli.Serialization.IppJsonHelper.Serialize({targetPropertyName}.{container}.{propName}) : {fieldName};");
                sb.AppendLine($"{indent}    set");
                sb.AppendLine($"{indent}    {{");
                sb.AppendLine($"{indent}        {fieldName} = value;");
                sb.AppendLine($"{indent}        if (!string.IsNullOrWhiteSpace(value))");
                sb.AppendLine($"{indent}        {{");
                sb.AppendLine($"{indent}            var parsed = IppCli.Serialization.IppJsonHelper.Deserialize<{cleanTypeName}>(value);");
                sb.AppendLine($"{indent}            if (parsed != null)");
                sb.AppendLine($"{indent}            {{");
                EmitContainerNullChecks(sb, indent, targetPropertyName, container);
                sb.AppendLine($"{indent}                {targetPropertyName}.{container}.{propName} = parsed;");
                sb.AppendLine($"{indent}            }}");
                sb.AppendLine($"{indent}        }}");
                sb.AppendLine($"{indent}    }}");
            }
        }

        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
    }

    private static void GenerateComplexArrayProperty(
        StringBuilder sb,
        string indent,
        string? container,
        string csharpPropName,
        string aliases,
        string propName,
        ITypeSymbol elemType,
        string targetPropertyName,
        string description)
    {
        var cleanElemTypeName = elemType.WithNullableAnnotation(NullableAnnotation.NotAnnotated).ToDisplayString();
        var fieldName = $"_{csharpPropName.Substring(0, 1).ToLowerInvariant()}{csharpPropName.Substring(1)}";

        sb.AppendLine($"{indent}private string? {fieldName};");
        sb.AppendLine($"{indent}[CommandOption(\"{aliases}\")]");
        sb.AppendLine($"{indent}[Description(\"{description}\")]");
        sb.AppendLine($"{indent}public string? {csharpPropName}");
        sb.AppendLine($"{indent}{{");
        if (string.IsNullOrEmpty(container))
        {
            sb.AppendLine($"{indent}    get => {targetPropertyName}.{propName} != null ? IppCli.Serialization.IppJsonHelper.Serialize({targetPropertyName}.{propName}) : {fieldName};");
            sb.AppendLine($"{indent}    set");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        {fieldName} = value;");
            sb.AppendLine($"{indent}        if (!string.IsNullOrWhiteSpace(value))");
            sb.AppendLine($"{indent}        {{");
            sb.AppendLine($"{indent}            var parsed = IppCli.Serialization.IppJsonHelper.Deserialize<{cleanElemTypeName}[]>(value);");
            sb.AppendLine($"{indent}            if (parsed != null)");
            sb.AppendLine($"{indent}            {{");
            sb.AppendLine($"{indent}                {targetPropertyName}.{propName} = parsed;");
            sb.AppendLine($"{indent}            }}");
            sb.AppendLine($"{indent}        }}");
            sb.AppendLine($"{indent}    }}");
        }
        else
        {
            sb.AppendLine($"{indent}    get => {targetPropertyName}.{GetSafePath(container)}?.{propName} != null ? IppCli.Serialization.IppJsonHelper.Serialize({targetPropertyName}.{container}.{propName}) : {fieldName};");
            sb.AppendLine($"{indent}    set");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        {fieldName} = value;");
            sb.AppendLine($"{indent}        if (!string.IsNullOrWhiteSpace(value))");
            sb.AppendLine($"{indent}        {{");
            sb.AppendLine($"{indent}            var parsed = IppCli.Serialization.IppJsonHelper.Deserialize<{cleanElemTypeName}[]>(value);");
            sb.AppendLine($"{indent}            if (parsed != null)");
            sb.AppendLine($"{indent}            {{");
            EmitContainerNullChecks(sb, indent, targetPropertyName, container);
            sb.AppendLine($"{indent}                {targetPropertyName}.{container}.{propName} = parsed;");
            sb.AppendLine($"{indent}            }}");
            sb.AppendLine($"{indent}        }}");
            sb.AppendLine($"{indent}    }}");
        }
        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
    }

    private static void GenerateContainerJsonOption(
        StringBuilder sb,
        string indent,
        string containerPropertyName,
        string propPrefix,
        string cliOption,
        INamedTypeSymbol attrType,
        string targetPropertyName)
    {
        var cleanTypeName = attrType.WithNullableAnnotation(NullableAnnotation.NotAnnotated).ToDisplayString();
        var csharpPropName = $"{propPrefix}Json";

        sb.AppendLine($"{indent}private string? _{csharpPropName.ToLowerInvariant()};");
        sb.AppendLine($"{indent}[CommandOption(\"{cliOption}\")]");
        sb.AppendLine($"{indent}[Description(\"JSON string or @file.json for {containerPropertyName}\")]");
        sb.AppendLine($"{indent}public string? {csharpPropName}");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    get => {targetPropertyName}.{containerPropertyName} != null ? IppCli.Serialization.IppJsonHelper.Serialize({targetPropertyName}.{containerPropertyName}) : _{csharpPropName.ToLowerInvariant()};");
        sb.AppendLine($"{indent}    set");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        _{csharpPropName.ToLowerInvariant()} = value;");
        sb.AppendLine($"{indent}        if (!string.IsNullOrWhiteSpace(value))");
        sb.AppendLine($"{indent}        {{");
        sb.AppendLine($"{indent}            var parsed = IppCli.Serialization.IppJsonHelper.Deserialize<{cleanTypeName}>(value);");
        sb.AppendLine($"{indent}            if (parsed != null)");
        sb.AppendLine($"{indent}            {{");
        sb.AppendLine($"{indent}                {targetPropertyName}.{containerPropertyName} = parsed;");
        sb.AppendLine($"{indent}            }}");
        sb.AppendLine($"{indent}        }}");
        sb.AppendLine($"{indent}    }}");
        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
    }

    private static bool IsAttributeGroup(IPropertySymbol member)
    {
        if (member.Type is not INamedTypeSymbol namedType)
            return false;

        if (namedType.TypeKind != TypeKind.Class)
            return false;

        if (IsStreamType(namedType)) return false;
        var unwrapped = GetUnwrappedType(namedType);
        if (unwrapped.SpecialType != SpecialType.None) return false;
        if (unwrapped.TypeKind == TypeKind.Enum) return false;
        if (unwrapped.AllInterfaces.Any(i => i.Name == "ISmartEnum")) return false;
        if (unwrapped.Name is "Uri" or "IppVersion" or "DateTimeOffset" or "String" or "Int32" or "Boolean" or "Stream") return false;

        return GetAllProperties(namedType).Count > 0;
    }

    private static (string PropPrefix, string CliPrefix, string SectionTitle, string JsonCliOption) GetAttributeGroupInfo(string containerName)
    {
        string acronym;
        if (containerName.Equals("OperationAttributes", StringComparison.OrdinalIgnoreCase))
        {
            acronym = "op";
        }
        else
        {
            var matches = Regex.Matches(containerName, @"[A-Z][a-z0-9]*");
            var sb = new StringBuilder();
            foreach (Match match in matches)
            {
                if (match.Value.Length > 0)
                {
                    sb.Append(char.ToLowerInvariant(match.Value[0]));
                }
            }
            acronym = sb.Length > 0 ? sb.ToString() : containerName.ToLowerInvariant();
        }

        var propPrefix = char.ToUpperInvariant(acronym[0]) + (acronym.Length > 1 ? acronym.Substring(1) : "");
        var cliPrefix = $"--{acronym}-";
        var sectionTitle = ToSectionTitle(containerName);
        var jsonCliOption = $"--{acronym} <JSON>";

        return (propPrefix, cliPrefix, sectionTitle, jsonCliOption);
    }

    private static string ToSectionTitle(string value)
    {
        if (string.IsNullOrEmpty(value)) return value;
        return Regex.Replace(value, "([a-z])([A-Z])", "$1 $2");
    }

    private static bool IsIppCollection(ITypeSymbol type)
    {
        var unwrapped = GetUnwrappedType(type);
        return unwrapped.AllInterfaces.Any(i => i.Name == "IIppCollection");
    }

    private static void GenerateRangeProperty(
        StringBuilder sb,
        string indent,
        string? container,
        string csharpPropName,
        string aliases,
        string propName,
        string targetPropertyName,
        string description)
    {
        sb.AppendLine($"{indent}[CommandOption(\"{aliases}\")]");
        sb.AppendLine($"{indent}[Description(\"{description}\")]");
        sb.AppendLine($"{indent}public string? {csharpPropName}");
        sb.AppendLine($"{indent}{{");
        if (string.IsNullOrEmpty(container))
        {
            sb.AppendLine($"{indent}    get => {targetPropertyName}.{propName}?.ToString();");
            sb.AppendLine($"{indent}    set");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        if (!string.IsNullOrWhiteSpace(value))");
            sb.AppendLine($"{indent}        {{");
            sb.AppendLine($"{indent}            var parts = value.Split('-');");
            sb.AppendLine($"{indent}            {targetPropertyName}.{propName} = parts.Length > 1 ? new SharpIpp.Protocol.Models.Range(int.Parse(parts[0]), int.Parse(parts[1])) : new SharpIpp.Protocol.Models.Range(int.Parse(parts[0]), int.Parse(parts[0]));");
            sb.AppendLine($"{indent}        }}");
            sb.AppendLine($"{indent}    }}");
        }
        else
        {
            sb.AppendLine($"{indent}    get => {targetPropertyName}.{GetSafePath(container)}?.{propName}?.ToString();");
            sb.AppendLine($"{indent}    set");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        if (!string.IsNullOrWhiteSpace(value))");
            sb.AppendLine($"{indent}        {{");
            EmitContainerNullChecks(sb, indent, targetPropertyName, container);
            sb.AppendLine($"{indent}            var parts = value.Split('-');");
            sb.AppendLine($"{indent}            {targetPropertyName}.{container}.{propName} = parts.Length > 1 ? new SharpIpp.Protocol.Models.Range(int.Parse(parts[0]), int.Parse(parts[1])) : new SharpIpp.Protocol.Models.Range(int.Parse(parts[0]), int.Parse(parts[0]));");
            sb.AppendLine($"{indent}        }}");
            sb.AppendLine($"{indent}    }}");
        }
        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
    }

    private static bool IsComplexType(ITypeSymbol type)
    {
        var unwrapped = GetUnwrappedType(type);
        if (unwrapped.TypeKind != TypeKind.Class) return false;
        if (unwrapped.SpecialType != SpecialType.None) return false;
        if (unwrapped.TypeKind == TypeKind.Enum) return false;
        if (unwrapped.AllInterfaces.Any(i => i.Name is "ISmartEnum" or "IEnumerable" or "ICollection" or "IList" or "IDictionary")) return false;
        if (unwrapped.Name is "Uri" or "IppVersion" or "DateTimeOffset" or "String" or "Int32" or "Boolean" or "Stream" or "Range" or "IdentifyAction" or "DocumentFormat" or "IppStructuredString") return false;
        return true;
    }

    private static string ToKebabCase(string value)
    {
        if (string.IsNullOrEmpty(value)) return value;
        return Regex.Replace(value, "(?<!^)([A-Z][a-z]|(?<=[a-z])[A-Z])", "-$1").Trim().ToLowerInvariant();
    }
}

